from Crypto.Cipher import AES
from Crypto.Protocol.KDF import HKDF
from Crypto.Hash import HMAC, SHA256
from Crypto.Util.Padding import pad ,unpad


def get_session_keys(psk, nonce_c, nonce_s):
    """
    Derives encryption and HMAC keys using HKDF

    Parameters:
        psk (bytes): 32 bytes randomly generated key known only to the client and server
        nonce_c (bytes): 32 bytes randomly generated by the client for the session keys
        nonce_s (bytes): 32 bytes randomly generated by the server for the session keys

    Returns:
        enc_key (bytes): 16 bytes used as the encryption keys in AES-128
        hmac_key (bytes): 32 bytes used as the HMAC key
    """

    # Salt binds keys to this handshake
    salt = nonce_c + nonce_s

    # Derive 48 bytes total:
    # 16 bytes AES key + 32 bytes HMAC key
    key_material = HKDF(
        master=psk,
        key_len=48,
        salt=salt,
        hashmod=SHA256,
        context=b"secure-file-transfer"
    )

    enc_key = key_material[:16]      # AES-128
    hmac_key = key_material[16:]     # HMAC-SHA256

    return enc_key, hmac_key


def symmetric_encrypy(packet, key):
    """
    Encrypts the packet using the encryption session key

    Parameters:
        packet (bytes): unencrypted file section
        key (bytes): 16 bytes session key

    Returns:
        ciphertext_packet (bytes): encrypted file section
        iv (bytes): 16 bytes used for encryption along with the key
    """
    cipher = AES.new(key, AES.MODE_CBC)
    ciphertext_packet = cipher.encrypt(pad(packet, AES.block_size))
    return ciphertext_packet, cipher.iv


def symmetric_decrypt(packet, iv, key):
    """
    Decrypts the packet using the encryption session key

    Parameters:
        packet (bytes): encrypted file section
        key (bytes): 16 bytes session key
        iv (bytes): 16 bytes used for decryption along with the key

    Returns:
        pt (bytes): unencrypted file section
    """
    try:
        cipher = AES.new(key, AES.MODE_CBC, iv)
        pt = unpad(cipher.decrypt(packet), AES.block_size)
        return pt
    except (ValueError, KeyError):
        print("Incorrect decryption")
        exit()


def compute_hmac(key, iv, ct):
    """
    computes the HMAC using the hmac session key

    Parameters:
        key (bytes): 32 bytes hmac session key
        iv (bytes): 32 bytes used for decryption along with the key
        ct (bytes): encrypted file section

    Returns:
        result (bytes): HMAC for integrity
    """
    h = HMAC.new(key, digestmod=SHA256)
    h.update(iv + ct)
    return h.digest()


def compare_hmac(hmac, key,iv,ct):
    """
    compares the received HMAC with the computed HMAC using the hmac session key

    Parameters:
        hmac (bytes): 32 bytes received as the HMAC
        key (bytes): 32 bytes hmac session key
        iv (bytes): 32 bytes used for decryption along with the key
        ct (bytes): encrypted file section

    Returns:
        result (bool): true if the HMAC matches
    """
    computed_hmac = compute_hmac(key, iv, ct)
    return computed_hmac == hmac


def compute_auth(psk, nonce_c, nonce_s):
    """
    computes the HMAC using the hmac session key for authentication during handshake

    Parameters:
        psk (bytes): 32 bytes randomly generated key known only to the client and server
        nonce_c (bytes): 32 bytes randomly generated by the client for the session keys
        nonce_s (bytes): 32 bytes randomly generated by the server for the session keys / Replaced
                        by the bytes for CLIENT when authenticating the client since nonce_s is not know by the client yet

    Returns:
        result (bytes): HMAC for authentication
    """
    h = HMAC.new(psk, digestmod=SHA256)
    h.update(nonce_c + nonce_s)
    return h.digest()